name: Build and push Docker image

on:
  push:
    tags:
      - '*.*.*'
jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set release version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      -
        name: Login to OCR
        uses: docker/login-action@v2.1.0
        with:
          registry: lhr.ocir.io
          username: ${{ secrets.OCR_USERNAME }}
          password: ${{ secrets.OCR_TOKEN }}
      -

        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          tags: |
            lhr.ocir.io/lrbvkel2wjot/gpas/client:latest
            lhr.ocir.io/lrbvkel2wjot/gpas/client:${{env.RELEASE_VERSION}}
          push: true
          no-cache: true
  