name: tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-14]
        python-version: ['3.10']
    name: Python ${{ matrix.python-version }} (${{ matrix.os }})
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        id: setup-miniconda
        continue-on-error: true
        with:
          python-version: ${{ matrix.python-version }}
          miniconda-version: latest
          channels: conda-forge, bioconda
          auto-activate-base: true
          activate-environment: ""
      - name: Install
        shell: bash -el {0}
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
              conda create -y -n pathogena-test -c conda-forge -c bioconda hostile==1.1.0
          elif [ "$RUNNER_OS" == "MacOS" ]; then
              conda create --platform osx-64 -y -n pathogena-test -c conda-forge -c bioconda hostile==1.1.0
          else
              echo "$RUNNER_OS not supported"
              exit 1
          fi
          conda activate pathogena-test
          pip install '.[dev]'
      - name: Format
        shell: bash -el {0}
        run: |
          python -m ruff format --check
      - name: Lint
        shell: bash -el {0}
        run: |
          python -m ruff check
      - name: Test
        shell: bash -el {0}
        run: |
          python -m pytest
