name: tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
        python-version: ['3.10']
    name: Python ${{ matrix.python-version }} (${{ matrix.os }})
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        id: setup-miniconda
        continue-on-error: true
        with:
          python-version: ${{ matrix.python-version }}
          miniconda-version: latest
          channels: conda-forge, bioconda
          activate-environment: pathogena-test
      - name: Install
        shell: bash -el {0}
        run: |
          conda env list
          conda install hostile==1.1.0
          pip install '.[dev]'
      - name: Format
        shell: bash -el {0}
        run: |
          python -m ruff format --check
      - name: Lint
        shell: bash -el {0}
        run: |
          python -m ruff check
      - name: Test
        shell: bash -el {0}
        run: |
          python -m pytest
