name: tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-14]
        python-version: ['3.10']
    name: Python ${{ matrix.python-version }} (${{ matrix.os }})
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        id: setup-miniconda
        continue-on-error: true
        with:
          miniconda-version: latest
          channels: conda-forge, bioconda
      - name: Check arm64
        shell: bash -el {0}
        run: |
          conda install -y python
          python -c "import platform; assert platform.machine() == 'arm64', platform.machine()"
      - name: Install
        run: |
          conda install hostile==1.1.0
          pip install '.[dev]'
      - name: Format
        run: |
          python -m ruff format --check
      - name: Lint
        run: |
          python -m ruff check
      - name: Test
        run: |
          python -m pytest
